//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GetData.zxjaUpdater {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="zxjaUpdater.DBUploaderSoap")]
    public interface DBUploaderSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 para 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DoAction", ReplyAction="*")]
        WS_GetData.zxjaUpdater.DoActionResponse DoAction(WS_GetData.zxjaUpdater.DoActionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoActionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoAction", Namespace="http://tempuri.org/", Order=0)]
        public WS_GetData.zxjaUpdater.DoActionRequestBody Body;
        
        public DoActionRequest() {
        }
        
        public DoActionRequest(WS_GetData.zxjaUpdater.DoActionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoActionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] para;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Tag1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Tag2;
        
        public DoActionRequestBody() {
        }
        
        public DoActionRequestBody(byte[] para, byte[] Tag1, byte[] Tag2) {
            this.para = para;
            this.Tag1 = Tag1;
            this.Tag2 = Tag2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DoActionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DoActionResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GetData.zxjaUpdater.DoActionResponseBody Body;
        
        public DoActionResponse() {
        }
        
        public DoActionResponse(WS_GetData.zxjaUpdater.DoActionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DoActionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DoActionResult;
        
        public DoActionResponseBody() {
        }
        
        public DoActionResponseBody(byte[] DoActionResult) {
            this.DoActionResult = DoActionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBUploaderSoapChannel : WS_GetData.zxjaUpdater.DBUploaderSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBUploaderSoapClient : System.ServiceModel.ClientBase<WS_GetData.zxjaUpdater.DBUploaderSoap>, WS_GetData.zxjaUpdater.DBUploaderSoap {
        
        public DBUploaderSoapClient() {
        }
        
        public DBUploaderSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBUploaderSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBUploaderSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBUploaderSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GetData.zxjaUpdater.DoActionResponse WS_GetData.zxjaUpdater.DBUploaderSoap.DoAction(WS_GetData.zxjaUpdater.DoActionRequest request) {
            return base.Channel.DoAction(request);
        }
        
        public byte[] DoAction(byte[] para, byte[] Tag1, byte[] Tag2) {
            WS_GetData.zxjaUpdater.DoActionRequest inValue = new WS_GetData.zxjaUpdater.DoActionRequest();
            inValue.Body = new WS_GetData.zxjaUpdater.DoActionRequestBody();
            inValue.Body.para = para;
            inValue.Body.Tag1 = Tag1;
            inValue.Body.Tag2 = Tag2;
            WS_GetData.zxjaUpdater.DoActionResponse retVal = ((WS_GetData.zxjaUpdater.DBUploaderSoap)(this)).DoAction(inValue);
            return retVal.Body.DoActionResult;
        }
    }
}
