//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GetData.BDYService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportCertDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ImportCertDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NativePlaceField;
        
        private int nativePlaceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationField;
        
        private int educationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        private int workIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkLevelField;
        
        private System.Nullable<int> workLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCertTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departmentNameField;
        
        private int departmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingEndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheoryScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperateScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SafetyScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorInfoField;
        
        private int CertTypeIdField;
        
        private int CertificateTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TWorkNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNameField;
        
        private System.DateTime CreatTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentName {
            get {
                return this.StudentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNameField, value) != true)) {
                    this.StudentNameField = value;
                    this.RaisePropertyChanged("StudentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string IDCard {
            get {
                return this.IDCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCardField, value) != true)) {
                    this.IDCardField = value;
                    this.RaisePropertyChanged("IDCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NativePlace {
            get {
                return this.NativePlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NativePlaceField, value) != true)) {
                    this.NativePlaceField = value;
                    this.RaisePropertyChanged("NativePlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int nativePlaceId {
            get {
                return this.nativePlaceIdField;
            }
            set {
                if ((this.nativePlaceIdField.Equals(value) != true)) {
                    this.nativePlaceIdField = value;
                    this.RaisePropertyChanged("nativePlaceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Education {
            get {
                return this.EducationField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationField, value) != true)) {
                    this.EducationField = value;
                    this.RaisePropertyChanged("Education");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int educationId {
            get {
                return this.educationIdField;
            }
            set {
                if ((this.educationIdField.Equals(value) != true)) {
                    this.educationIdField = value;
                    this.RaisePropertyChanged("educationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string WorkAge {
            get {
                return this.WorkAgeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkAgeField, value) != true)) {
                    this.WorkAgeField = value;
                    this.RaisePropertyChanged("WorkAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string WorkUnit {
            get {
                return this.WorkUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkUnitField, value) != true)) {
                    this.WorkUnitField = value;
                    this.RaisePropertyChanged("WorkUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ExamUnit {
            get {
                return this.ExamUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamUnitField, value) != true)) {
                    this.ExamUnitField = value;
                    this.RaisePropertyChanged("ExamUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string CertificateDepartment {
            get {
                return this.CertificateDepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateDepartmentField, value) != true)) {
                    this.CertificateDepartmentField = value;
                    this.RaisePropertyChanged("CertificateDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string WorkName {
            get {
                return this.WorkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkNameField, value) != true)) {
                    this.WorkNameField = value;
                    this.RaisePropertyChanged("WorkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int workId {
            get {
                return this.workIdField;
            }
            set {
                if ((this.workIdField.Equals(value) != true)) {
                    this.workIdField = value;
                    this.RaisePropertyChanged("workId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string WorkLevel {
            get {
                return this.WorkLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkLevelField, value) != true)) {
                    this.WorkLevelField = value;
                    this.RaisePropertyChanged("WorkLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<int> workLevelId {
            get {
                return this.workLevelIdField;
            }
            set {
                if ((this.workLevelIdField.Equals(value) != true)) {
                    this.workLevelIdField = value;
                    this.RaisePropertyChanged("workLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string CertNum {
            get {
                return this.CertNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CertNumField, value) != true)) {
                    this.CertNumField = value;
                    this.RaisePropertyChanged("CertNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string GetCertTime {
            get {
                return this.GetCertTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCertTimeField, value) != true)) {
                    this.GetCertTimeField = value;
                    this.RaisePropertyChanged("GetCertTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string departmentName {
            get {
                return this.departmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.departmentNameField, value) != true)) {
                    this.departmentNameField = value;
                    this.RaisePropertyChanged("departmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public int departmentId {
            get {
                return this.departmentIdField;
            }
            set {
                if ((this.departmentIdField.Equals(value) != true)) {
                    this.departmentIdField = value;
                    this.RaisePropertyChanged("departmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string TrainingStartTime {
            get {
                return this.TrainingStartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingStartTimeField, value) != true)) {
                    this.TrainingStartTimeField = value;
                    this.RaisePropertyChanged("TrainingStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string TrainingEndTime {
            get {
                return this.TrainingEndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingEndTimeField, value) != true)) {
                    this.TrainingEndTimeField = value;
                    this.RaisePropertyChanged("TrainingEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string TrainingHours {
            get {
                return this.TrainingHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingHoursField, value) != true)) {
                    this.TrainingHoursField = value;
                    this.RaisePropertyChanged("TrainingHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string TheoryScore {
            get {
                return this.TheoryScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.TheoryScoreField, value) != true)) {
                    this.TheoryScoreField = value;
                    this.RaisePropertyChanged("TheoryScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string OperateScore {
            get {
                return this.OperateScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.OperateScoreField, value) != true)) {
                    this.OperateScoreField = value;
                    this.RaisePropertyChanged("OperateScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string SafetyScore {
            get {
                return this.SafetyScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.SafetyScoreField, value) != true)) {
                    this.SafetyScoreField = value;
                    this.RaisePropertyChanged("SafetyScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string OtherScore {
            get {
                return this.OtherScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherScoreField, value) != true)) {
                    this.OtherScoreField = value;
                    this.RaisePropertyChanged("OtherScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string ErrorInfo {
            get {
                return this.ErrorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInfoField, value) != true)) {
                    this.ErrorInfoField = value;
                    this.RaisePropertyChanged("ErrorInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public int CertTypeId {
            get {
                return this.CertTypeIdField;
            }
            set {
                if ((this.CertTypeIdField.Equals(value) != true)) {
                    this.CertTypeIdField = value;
                    this.RaisePropertyChanged("CertTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public int CertificateTypeId {
            get {
                return this.CertificateTypeIdField;
            }
            set {
                if ((this.CertificateTypeIdField.Equals(value) != true)) {
                    this.CertificateTypeIdField = value;
                    this.RaisePropertyChanged("CertificateTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string CertTypeName {
            get {
                return this.CertTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CertTypeNameField, value) != true)) {
                    this.CertTypeNameField = value;
                    this.RaisePropertyChanged("CertTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string CertName {
            get {
                return this.CertNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CertNameField, value) != true)) {
                    this.CertNameField = value;
                    this.RaisePropertyChanged("CertName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string TWorkNum {
            get {
                return this.TWorkNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TWorkNumField, value) != true)) {
                    this.TWorkNumField = value;
                    this.RaisePropertyChanged("TWorkNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string Profession {
            get {
                return this.ProfessionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfessionField, value) != true)) {
                    this.ProfessionField = value;
                    this.RaisePropertyChanged("Profession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string CertState {
            get {
                return this.CertStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CertStateField, value) != true)) {
                    this.CertStateField = value;
                    this.RaisePropertyChanged("CertState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string AddJob {
            get {
                return this.AddJobField;
            }
            set {
                if ((object.ReferenceEquals(this.AddJobField, value) != true)) {
                    this.AddJobField = value;
                    this.RaisePropertyChanged("AddJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string EducationLog {
            get {
                return this.EducationLogField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationLogField, value) != true)) {
                    this.EducationLogField = value;
                    this.RaisePropertyChanged("EducationLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string JobName {
            get {
                return this.JobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNameField, value) != true)) {
                    this.JobNameField = value;
                    this.RaisePropertyChanged("JobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=40)]
        public System.DateTime CreatTime {
            get {
                return this.CreatTimeField;
            }
            set {
                if ((this.CreatTimeField.Equals(value) != true)) {
                    this.CreatTimeField = value;
                    this.RaisePropertyChanged("CreatTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BDYService.ZhuJianServiceSoap")]
    public interface ZhuJianServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 CertList 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadCert", ReplyAction="*")]
        WS_GetData.BDYService.UploadCertResponse UploadCert(WS_GetData.BDYService.UploadCertRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 CertList 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadProfessionCert", ReplyAction="*")]
        WS_GetData.BDYService.UploadProfessionCertResponse UploadProfessionCert(WS_GetData.BDYService.UploadProfessionCertRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadCert", Namespace="http://tempuri.org/", Order=0)]
        public WS_GetData.BDYService.UploadCertRequestBody Body;
        
        public UploadCertRequest() {
        }
        
        public UploadCertRequest(WS_GetData.BDYService.UploadCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadCertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GetData.BDYService.ImportCertDTO[] CertList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AdminName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdminPwd;
        
        public UploadCertRequestBody() {
        }
        
        public UploadCertRequestBody(WS_GetData.BDYService.ImportCertDTO[] CertList, string AdminName, string AdminPwd) {
            this.CertList = CertList;
            this.AdminName = AdminName;
            this.AdminPwd = AdminPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GetData.BDYService.UploadCertResponseBody Body;
        
        public UploadCertResponse() {
        }
        
        public UploadCertResponse(WS_GetData.BDYService.UploadCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadCertResult;
        
        public UploadCertResponseBody() {
        }
        
        public UploadCertResponseBody(string UploadCertResult) {
            this.UploadCertResult = UploadCertResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadProfessionCertRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadProfessionCert", Namespace="http://tempuri.org/", Order=0)]
        public WS_GetData.BDYService.UploadProfessionCertRequestBody Body;
        
        public UploadProfessionCertRequest() {
        }
        
        public UploadProfessionCertRequest(WS_GetData.BDYService.UploadProfessionCertRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadProfessionCertRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_GetData.BDYService.ImportCertDTO[] CertList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AdminName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AdminPwd;
        
        public UploadProfessionCertRequestBody() {
        }
        
        public UploadProfessionCertRequestBody(WS_GetData.BDYService.ImportCertDTO[] CertList, string AdminName, string AdminPwd) {
            this.CertList = CertList;
            this.AdminName = AdminName;
            this.AdminPwd = AdminPwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadProfessionCertResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadProfessionCertResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_GetData.BDYService.UploadProfessionCertResponseBody Body;
        
        public UploadProfessionCertResponse() {
        }
        
        public UploadProfessionCertResponse(WS_GetData.BDYService.UploadProfessionCertResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadProfessionCertResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadProfessionCertResult;
        
        public UploadProfessionCertResponseBody() {
        }
        
        public UploadProfessionCertResponseBody(string UploadProfessionCertResult) {
            this.UploadProfessionCertResult = UploadProfessionCertResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZhuJianServiceSoapChannel : WS_GetData.BDYService.ZhuJianServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZhuJianServiceSoapClient : System.ServiceModel.ClientBase<WS_GetData.BDYService.ZhuJianServiceSoap>, WS_GetData.BDYService.ZhuJianServiceSoap {
        
        public ZhuJianServiceSoapClient() {
        }
        
        public ZhuJianServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZhuJianServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZhuJianServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZhuJianServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GetData.BDYService.UploadCertResponse WS_GetData.BDYService.ZhuJianServiceSoap.UploadCert(WS_GetData.BDYService.UploadCertRequest request) {
            return base.Channel.UploadCert(request);
        }
        
        public string UploadCert(WS_GetData.BDYService.ImportCertDTO[] CertList, string AdminName, string AdminPwd) {
            WS_GetData.BDYService.UploadCertRequest inValue = new WS_GetData.BDYService.UploadCertRequest();
            inValue.Body = new WS_GetData.BDYService.UploadCertRequestBody();
            inValue.Body.CertList = CertList;
            inValue.Body.AdminName = AdminName;
            inValue.Body.AdminPwd = AdminPwd;
            WS_GetData.BDYService.UploadCertResponse retVal = ((WS_GetData.BDYService.ZhuJianServiceSoap)(this)).UploadCert(inValue);
            return retVal.Body.UploadCertResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GetData.BDYService.UploadProfessionCertResponse WS_GetData.BDYService.ZhuJianServiceSoap.UploadProfessionCert(WS_GetData.BDYService.UploadProfessionCertRequest request) {
            return base.Channel.UploadProfessionCert(request);
        }
        
        public string UploadProfessionCert(WS_GetData.BDYService.ImportCertDTO[] CertList, string AdminName, string AdminPwd) {
            WS_GetData.BDYService.UploadProfessionCertRequest inValue = new WS_GetData.BDYService.UploadProfessionCertRequest();
            inValue.Body = new WS_GetData.BDYService.UploadProfessionCertRequestBody();
            inValue.Body.CertList = CertList;
            inValue.Body.AdminName = AdminName;
            inValue.Body.AdminPwd = AdminPwd;
            WS_GetData.BDYService.UploadProfessionCertResponse retVal = ((WS_GetData.BDYService.ZhuJianServiceSoap)(this)).UploadProfessionCert(inValue);
            return retVal.Body.UploadProfessionCertResult;
        }
    }
}
