//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GetData.RYKWXT {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RYKWXT.InterFaceServiceSoap")]
    public interface InterFaceServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSystemId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSourceServiceHttp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDataSourceServiceHttp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryTable(out int recordCount, string systemId, string serviceId, string tableName, int startIndex, int pageSize, string condition, string sortText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryService(out int recordCount, string serviceId, string tableName, int startIndex, int pageSize, string condition, string sortText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddData(string userName, string passWord, string iServiceId, System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateData(string userName, string passWord, string iServiceId, System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleData(string userName, string passWord, string iServiceId, System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryData(out int resultCount, string userName, string passWord, string iServiceId, string tableName, int startIndex, int pageSize, string condition, string sortText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryDataToLargeData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet QueryDataToLargeData(out int resultCount, out int pageCount, string userName, string passWord, string iServiceId, string tableName, int startIndex, int pageSize, string condition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PageQueryData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PageQueryData(out int resultCount, string userName, string passWord, string iServiceId, string tableName, int pageIndex, int pageSize, string condition, string sortText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIServiceStruct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIServiceStruct(string userName, string passWord, string iServiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIServiceFieldsCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIServiceFieldsCollection(string userName, string passWord, string iServiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceFieldsCollection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServiceFieldsCollection(string userName, string passWord, string serviceId, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddExchTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddExchTask(System.DateTime exeTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpDateExchServiceNextExeTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpDateExchServiceNextExeTime(System.DateTime exeTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExchServiceLogByIsRunNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetExchServiceLogByIsRunNo(System.DateTime exeTime, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExchServiceLogByIsSucessIsCompare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetExchServiceLogByIsSucessIsCompare(System.DateTime exeTime, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateServiceLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateServiceLog(string eServiceLogId, int isSuccess, int isRun, string errorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateServiceLogCompare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateServiceLogCompare(string eServiceLogId, int compareIsRun, int compareSuccess, string errorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertServiceTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertServiceTask(string eServiceTaskId, string eServiceId, string eServiceLogId, int pageIndex, int startIndex, int endIndex, int getSuccess, int insertSuccess, string errorInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExchServiceCompareFields", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetExchServiceCompareFields(string EServiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryDataToHtml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string QueryDataToHtml(out int resultCount, string userName, string passWord, string iServiceId, string tableName, int startIndex, int pageSize, string condition, string sortText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckAvail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckAvail(out int stateCollection, string userName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GetUserInfo(out WS_GetData.RYKWXT.Sys_User user, string userName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceCategoryTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServiceCategoryTable(string userName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetServiceListByServiceCategoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetServiceListByServiceCategoryId(string userName, string pwd, string serviceCategoryId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sys_User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string deptIdField;
        
        private string nameField;
        
        private string pwdField;
        
        private string sfzField;
        
        private string emailField;
        
        private string telField;
        
        private string mobileField;
        
        private string dutyArrayField;
        
        private string serviceRightField;
        
        private string menuRightField;
        
        private System.DateTime endTimeField;
        
        private string flagField;
        
        private string deptArrayField;
        
        private string reportArrayField;
        
        private string reportDeptArrayField;
        
        private string allMenuRightField;
        
        private string allServiceRightField;
        
        private string cServiceRightField;
        
        private string allCServieRightField;
        
        private string allReportRightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DeptId {
            get {
                return this.deptIdField;
            }
            set {
                this.deptIdField = value;
                this.RaisePropertyChanged("DeptId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
                this.RaisePropertyChanged("Pwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sfz {
            get {
                return this.sfzField;
            }
            set {
                this.sfzField = value;
                this.RaisePropertyChanged("Sfz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
                this.RaisePropertyChanged("Tel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
                this.RaisePropertyChanged("Mobile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DutyArray {
            get {
                return this.dutyArrayField;
            }
            set {
                this.dutyArrayField = value;
                this.RaisePropertyChanged("DutyArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ServiceRight {
            get {
                return this.serviceRightField;
            }
            set {
                this.serviceRightField = value;
                this.RaisePropertyChanged("ServiceRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MenuRight {
            get {
                return this.menuRightField;
            }
            set {
                this.menuRightField = value;
                this.RaisePropertyChanged("MenuRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
                this.RaisePropertyChanged("EndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DeptArray {
            get {
                return this.deptArrayField;
            }
            set {
                this.deptArrayField = value;
                this.RaisePropertyChanged("DeptArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ReportArray {
            get {
                return this.reportArrayField;
            }
            set {
                this.reportArrayField = value;
                this.RaisePropertyChanged("ReportArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ReportDeptArray {
            get {
                return this.reportDeptArrayField;
            }
            set {
                this.reportDeptArrayField = value;
                this.RaisePropertyChanged("ReportDeptArray");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AllMenuRight {
            get {
                return this.allMenuRightField;
            }
            set {
                this.allMenuRightField = value;
                this.RaisePropertyChanged("AllMenuRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AllServiceRight {
            get {
                return this.allServiceRightField;
            }
            set {
                this.allServiceRightField = value;
                this.RaisePropertyChanged("AllServiceRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CServiceRight {
            get {
                return this.cServiceRightField;
            }
            set {
                this.cServiceRightField = value;
                this.RaisePropertyChanged("CServiceRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string AllCServieRight {
            get {
                return this.allCServieRightField;
            }
            set {
                this.allCServieRightField = value;
                this.RaisePropertyChanged("AllCServieRight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string AllReportRight {
            get {
                return this.allReportRightField;
            }
            set {
                this.allReportRightField = value;
                this.RaisePropertyChanged("AllReportRight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InterFaceServiceSoapChannel : WS_GetData.RYKWXT.InterFaceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterFaceServiceSoapClient : System.ServiceModel.ClientBase<WS_GetData.RYKWXT.InterFaceServiceSoap>, WS_GetData.RYKWXT.InterFaceServiceSoap {
        
        public InterFaceServiceSoapClient() {
        }
        
        public InterFaceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterFaceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterFaceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterFaceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetSystemId() {
            return base.Channel.GetSystemId();
        }
        
        public string GetDataSourceServiceHttp() {
            return base.Channel.GetDataSourceServiceHttp();
        }
        
        public System.Data.DataSet QueryTable(out int recordCount, string systemId, string serviceId, string tableName, int startIndex, int pageSize, string condition, string sortText) {
            return base.Channel.QueryTable(out recordCount, systemId, serviceId, tableName, startIndex, pageSize, condition, sortText);
        }
        
        public System.Data.DataSet QueryService(out int recordCount, string serviceId, string tableName, int startIndex, int pageSize, string condition, string sortText) {
            return base.Channel.QueryService(out recordCount, serviceId, tableName, startIndex, pageSize, condition, sortText);
        }
        
        public bool AddData(string userName, string passWord, string iServiceId, System.Data.DataSet ds) {
            return base.Channel.AddData(userName, passWord, iServiceId, ds);
        }
        
        public bool UpdateData(string userName, string passWord, string iServiceId, System.Data.DataSet ds) {
            return base.Channel.UpdateData(userName, passWord, iServiceId, ds);
        }
        
        public bool DeleData(string userName, string passWord, string iServiceId, System.Data.DataSet ds) {
            return base.Channel.DeleData(userName, passWord, iServiceId, ds);
        }
        
        public System.Data.DataSet QueryData(out int resultCount, string userName, string passWord, string iServiceId, string tableName, int startIndex, int pageSize, string condition, string sortText) {
            return base.Channel.QueryData(out resultCount, userName, passWord, iServiceId, tableName, startIndex, pageSize, condition, sortText);
        }
        
        public System.Data.DataSet QueryDataToLargeData(out int resultCount, out int pageCount, string userName, string passWord, string iServiceId, string tableName, int startIndex, int pageSize, string condition) {
            return base.Channel.QueryDataToLargeData(out resultCount, out pageCount, userName, passWord, iServiceId, tableName, startIndex, pageSize, condition);
        }
        
        public System.Data.DataSet PageQueryData(out int resultCount, string userName, string passWord, string iServiceId, string tableName, int pageIndex, int pageSize, string condition, string sortText) {
            return base.Channel.PageQueryData(out resultCount, userName, passWord, iServiceId, tableName, pageIndex, pageSize, condition, sortText);
        }
        
        public System.Data.DataSet GetIServiceStruct(string userName, string passWord, string iServiceId) {
            return base.Channel.GetIServiceStruct(userName, passWord, iServiceId);
        }
        
        public System.Data.DataSet GetIServiceFieldsCollection(string userName, string passWord, string iServiceId) {
            return base.Channel.GetIServiceFieldsCollection(userName, passWord, iServiceId);
        }
        
        public System.Data.DataSet GetServiceFieldsCollection(string userName, string passWord, string serviceId, string tableName) {
            return base.Channel.GetServiceFieldsCollection(userName, passWord, serviceId, tableName);
        }
        
        public bool AddExchTask(System.DateTime exeTime) {
            return base.Channel.AddExchTask(exeTime);
        }
        
        public bool UpDateExchServiceNextExeTime(System.DateTime exeTime) {
            return base.Channel.UpDateExchServiceNextExeTime(exeTime);
        }
        
        public System.Data.DataSet GetExchServiceLogByIsRunNo(System.DateTime exeTime, string tableName) {
            return base.Channel.GetExchServiceLogByIsRunNo(exeTime, tableName);
        }
        
        public System.Data.DataSet GetExchServiceLogByIsSucessIsCompare(System.DateTime exeTime, string tableName) {
            return base.Channel.GetExchServiceLogByIsSucessIsCompare(exeTime, tableName);
        }
        
        public bool UpdateServiceLog(string eServiceLogId, int isSuccess, int isRun, string errorInfo) {
            return base.Channel.UpdateServiceLog(eServiceLogId, isSuccess, isRun, errorInfo);
        }
        
        public bool UpdateServiceLogCompare(string eServiceLogId, int compareIsRun, int compareSuccess, string errorInfo) {
            return base.Channel.UpdateServiceLogCompare(eServiceLogId, compareIsRun, compareSuccess, errorInfo);
        }
        
        public bool InsertServiceTask(string eServiceTaskId, string eServiceId, string eServiceLogId, int pageIndex, int startIndex, int endIndex, int getSuccess, int insertSuccess, string errorInfo) {
            return base.Channel.InsertServiceTask(eServiceTaskId, eServiceId, eServiceLogId, pageIndex, startIndex, endIndex, getSuccess, insertSuccess, errorInfo);
        }
        
        public System.Data.DataSet GetExchServiceCompareFields(string EServiceId) {
            return base.Channel.GetExchServiceCompareFields(EServiceId);
        }
        
        public string QueryDataToHtml(out int resultCount, string userName, string passWord, string iServiceId, string tableName, int startIndex, int pageSize, string condition, string sortText) {
            return base.Channel.QueryDataToHtml(out resultCount, userName, passWord, iServiceId, tableName, startIndex, pageSize, condition, sortText);
        }
        
        public bool CheckAvail(out int stateCollection, string userName, string pwd) {
            return base.Channel.CheckAvail(out stateCollection, userName, pwd);
        }
        
        public bool GetUserInfo(out WS_GetData.RYKWXT.Sys_User user, string userName, string pwd) {
            return base.Channel.GetUserInfo(out user, userName, pwd);
        }
        
        public System.Data.DataSet GetServiceCategoryTable(string userName, string pwd) {
            return base.Channel.GetServiceCategoryTable(userName, pwd);
        }
        
        public System.Data.DataSet GetServiceListByServiceCategoryId(string userName, string pwd, string serviceCategoryId) {
            return base.Channel.GetServiceListByServiceCategoryId(userName, pwd, serviceCategoryId);
        }
    }
}
