//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GetData.FileService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileService.FileServiceSoap")]
    public interface FileServiceSoap {
        
        // CODEGEN: 参数“buffer”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WS_GetData.FileService.UploadFileResponse UploadFile(WS_GetData.FileService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteFileInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WriteFileInfo(string userName, string passWord, string iServiceId, System.Data.DataSet ds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIServiceStruct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetIServiceStruct(out System.Data.DataSet ds, string userName, string passWord, string iServiceId);
        
        // CODEGEN: 参数“buffer”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileWithInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WS_GetData.FileService.UploadFileWithInfoResponse UploadFileWithInfo(WS_GetData.FileService.UploadFileWithInfoRequest request);
        
        // CODEGEN: 参数“fileContent”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WS_GetData.FileService.DownloadFileResponse DownloadFile(WS_GetData.FileService.DownloadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileUrl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFileUrl(out string fileUrl, string userName, string passWord, string iServiceId, string fileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetFileInfo(out int resultCount, out System.Data.DataSet result, string userName, string passWord, string iServiceId, int pageIndex, int pageSize, string condition, string sortText);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string passWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string iServiceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string fileFullName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] buffer;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(string userName, string passWord, string iServiceId, string fileFullName, byte[] buffer) {
            this.userName = userName;
            this.passWord = passWord;
            this.iServiceId = iServiceId;
            this.fileFullName = fileFullName;
            this.buffer = buffer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileWithInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileWithInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string passWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string iServiceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Data.DataSet ds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] buffer;
        
        public UploadFileWithInfoRequest() {
        }
        
        public UploadFileWithInfoRequest(string userName, string passWord, string iServiceId, System.Data.DataSet ds, byte[] buffer) {
            this.userName = userName;
            this.passWord = passWord;
            this.iServiceId = iServiceId;
            this.ds = ds;
            this.buffer = buffer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileWithInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileWithInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string UploadFileWithInfoResult;
        
        public UploadFileWithInfoResponse() {
        }
        
        public UploadFileWithInfoResponse(string UploadFileWithInfoResult) {
            this.UploadFileWithInfoResult = UploadFileWithInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string passWord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string iServiceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string fileID;
        
        public DownloadFileRequest() {
        }
        
        public DownloadFileRequest(string userName, string passWord, string iServiceId, string fileID) {
            this.userName = userName;
            this.passWord = passWord;
            this.iServiceId = iServiceId;
            this.fileID = fileID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string DownloadFileResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] fileContent;
        
        public DownloadFileResponse() {
        }
        
        public DownloadFileResponse(string DownloadFileResult, byte[] fileContent) {
            this.DownloadFileResult = DownloadFileResult;
            this.fileContent = fileContent;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileServiceSoapChannel : WS_GetData.FileService.FileServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServiceSoapClient : System.ServiceModel.ClientBase<WS_GetData.FileService.FileServiceSoap>, WS_GetData.FileService.FileServiceSoap {
        
        public FileServiceSoapClient() {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GetData.FileService.UploadFileResponse WS_GetData.FileService.FileServiceSoap.UploadFile(WS_GetData.FileService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(string userName, string passWord, string iServiceId, string fileFullName, byte[] buffer) {
            WS_GetData.FileService.UploadFileRequest inValue = new WS_GetData.FileService.UploadFileRequest();
            inValue.userName = userName;
            inValue.passWord = passWord;
            inValue.iServiceId = iServiceId;
            inValue.fileFullName = fileFullName;
            inValue.buffer = buffer;
            WS_GetData.FileService.UploadFileResponse retVal = ((WS_GetData.FileService.FileServiceSoap)(this)).UploadFile(inValue);
            return retVal.UploadFileResult;
        }
        
        public string WriteFileInfo(string userName, string passWord, string iServiceId, System.Data.DataSet ds) {
            return base.Channel.WriteFileInfo(userName, passWord, iServiceId, ds);
        }
        
        public string GetIServiceStruct(out System.Data.DataSet ds, string userName, string passWord, string iServiceId) {
            return base.Channel.GetIServiceStruct(out ds, userName, passWord, iServiceId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GetData.FileService.UploadFileWithInfoResponse WS_GetData.FileService.FileServiceSoap.UploadFileWithInfo(WS_GetData.FileService.UploadFileWithInfoRequest request) {
            return base.Channel.UploadFileWithInfo(request);
        }
        
        public string UploadFileWithInfo(string userName, string passWord, string iServiceId, System.Data.DataSet ds, byte[] buffer) {
            WS_GetData.FileService.UploadFileWithInfoRequest inValue = new WS_GetData.FileService.UploadFileWithInfoRequest();
            inValue.userName = userName;
            inValue.passWord = passWord;
            inValue.iServiceId = iServiceId;
            inValue.ds = ds;
            inValue.buffer = buffer;
            WS_GetData.FileService.UploadFileWithInfoResponse retVal = ((WS_GetData.FileService.FileServiceSoap)(this)).UploadFileWithInfo(inValue);
            return retVal.UploadFileWithInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS_GetData.FileService.DownloadFileResponse WS_GetData.FileService.FileServiceSoap.DownloadFile(WS_GetData.FileService.DownloadFileRequest request) {
            return base.Channel.DownloadFile(request);
        }
        
        public string DownloadFile(string userName, string passWord, string iServiceId, string fileID, out byte[] fileContent) {
            WS_GetData.FileService.DownloadFileRequest inValue = new WS_GetData.FileService.DownloadFileRequest();
            inValue.userName = userName;
            inValue.passWord = passWord;
            inValue.iServiceId = iServiceId;
            inValue.fileID = fileID;
            WS_GetData.FileService.DownloadFileResponse retVal = ((WS_GetData.FileService.FileServiceSoap)(this)).DownloadFile(inValue);
            fileContent = retVal.fileContent;
            return retVal.DownloadFileResult;
        }
        
        public string GetFileUrl(out string fileUrl, string userName, string passWord, string iServiceId, string fileID) {
            return base.Channel.GetFileUrl(out fileUrl, userName, passWord, iServiceId, fileID);
        }
        
        public string GetFileInfo(out int resultCount, out System.Data.DataSet result, string userName, string passWord, string iServiceId, int pageIndex, int pageSize, string condition, string sortText) {
            return base.Channel.GetFileInfo(out resultCount, out result, userName, passWord, iServiceId, pageIndex, pageSize, condition, sortText);
        }
    }
}
